name: Build and Deploy to Strato

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Copy files to Strato via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ssh.strato.de
          username: youruser
          key: ${{ secrets.STRATO_SSH_KEY }}
          source: dist/*
          target: /home/youruser/my-vite-site
